#!/bin/bash
# bash required to pass awk args in an array

find_pack() {
  # using sed because builtins would require iterating
  # GNU basic regular expressions (BREs) require \| to use alternation
  sedargs="s,<a href=\",,g; \
    s,</a>,,g; \
    /^<h\|^<b\|<\/\|sig/d; \
    s,\".*,,"
  readonly sedargs
  output="$(sed "${sedargs}" <(printf %s "${1}") \
    | sort \
    | tail -n 1)"
  echo "$output"
}

main() {
  if [ ! -e template ]; then
    echo "No template in current directory." 1>&2 && exit 1
  fi

  readonly GCCLIBSURL="https://archive.archlinux.org/packages/g/gcc-libs"
  readonly GLIBCURL="https://github.com/sgerrand/alpine-pkg-glibc/releases"
  readonly ZLIBURL="https://archive.archlinux.org/packages/z/zlib"
  readonly SGKEYURL="https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub"

  readonly SGKEY="$(curl -LfsS ${SGKEYURL})"

  GCCFILE="$(curl -LfsS ${GCCLIBSURL})" \
    && GCCFILE="$(find_pack "${GCCFILE}")" \
    && readonly GCCFILE \
    || exit 1
  ZLIBFILE="$(curl -LfsS ${ZLIBURL})" \
    && ZLIBFILE="$(find_pack "${ZLIBFILE}")" \
    && readonly ZLIBFILE \
    || exit 1
  GLIBCVER="$(curl -sS ${GLIBCURL}/latest)" \
    && GLIBCVER="${GLIBCVER#*tag/}" \
    && GLIBCVER="${GLIBCVER%\"*}" \
    && readonly GLIBCVER \
    || exit 1

  readonly GCCTAR="${GCCFILE%????}"
  readonly GCCFULLURL="${GCCLIBSURL}/${GCCFILE}"
  readonly ZLIBFULLURL="${ZLIBURL}/${ZLIBFILE}"
  readonly GLIBCFULLURL="${GLIBCURL}/download/${GLIBCVER}/glibc-${GLIBCVER}.apk"
  readonly GLIBCBINURL="${GLIBCURL}/download/${GLIBCVER}/glibc-bin-${GLIBCVER}.apk"
  readonly GLIBCI18NURL="${GLIBCURL}/download/${GLIBCVER}/glibc-i18n-${GLIBCVER}.apk"
  readonly GLIBCFILE="glibc-$GLIBCVER.apk"
  readonly GLIBCBINFILE="glibc-bin-$GLIBCVER.apk"
  readonly GLIBCI18NFILE="glibc-i18n-$GLIBCVER.apk"
  readonly GCCLIBSVER="${GCCFILE%\.pkg*}"
  readonly ZLIBVER="${ZLIBFILE%\.pkg*}"

  if [ ! -d working ]; then
    mkdir /working
  fi
  cp template /working/template
  cd /working || exit 1
  # file downloads are slow; output not suppressed to show script did not hang
  curl -Lf "${GCCFULLURL}" "${ZLIBFULLURL}" -O -O \
    || exit 1
  curl -Lf "${GLIBCFULLURL}" "${GLIBCBINURL}" "${GLIBCI18NURL}" -O -O -O \
    || exit 1

  declare -a sums
  for file in *; do
    sums+=("$(sha256sum "${file}" | head -c 64)")
  done
  readonly sums

  # indices are hardcoded to assume only these five (5) files in this order
  readonly GCCSUM="${sums[0]}"
  readonly GLIBCSUM="${sums[1]}"
  readonly GLIBCBINSUM="${sums[2]}"
  readonly GLIBCI18NSUM="${sums[3]}"
  readonly ZLIBSUM="${sums[4]}"

  sed -i "s,GCCFULLURL,${GCCFULLURL},; \
    s,GLIBCFULLURL,${GLIBCFULLURL},; \
    s,GLIBCBINURL,${GLIBCBINURL},; \
    s,GLIBCI18NURL,${GLIBCI18NURL},; \
    s,ZLIBFULLURL,${ZLIBFULLURL},; \
    s,GCCFILE,${GCCFILE},; \
    s,GCCSUM,${GCCSUM},; \
    s,GCCTAR,${GCCTAR},; \
    s,GLIBCFILE,${GLIBCFILE},; \
    s,GLIBCSUM,${GLIBCSUM},; \
    s,GLIBCBINFILE,${GLIBCBINFILE},; \
    s,GLIBCBINSUM,${GLIBCBINSUM},; \
    s,GLIBCI18NFILE,${GLIBCI18NFILE},; \
    s,GLIBCI18NSUM,${GLIBCI18NSUM},; \
    s,SGKEYURL,${SGKEYURL},; \
    s,SGKEY,${SGKEY},; \
    s,ZLIBFILE,${ZLIBFILE},; \
    s,ZLIBSUM,${ZLIBSUM},; \
    s,GCCLIBSVER,${GCCLIBSVER},; \
    s,ZLIBVER,${ZLIBVER},; \
    s,GLIBCVER,${GLIBCVER},g" template
    # GCCLIBSVER unused in template
    # ZLIBVER unused in template
 cat template
}

main
exit 0
