name: Build and cache the Docker container

on:
  push:
    branches:
      - testing

jobs:
  trystable:
    # needs: prepare
    name: Build and tag the stable image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          # TODO look for ways to optimize the container layer caching process
          path: ./builds/stable/.buildx-cache
          key: buildx-stable-${{ github.sha }}
          restore-keys: |
            buildx-stable-
      -
        name: Build and cache the stable container
        uses: docker/build-push-action@v2
        with:
          file: ./builds/stable/Dockerfile
          build-args: JDK_VERSION=15
          tags: ethco/jlinkmc:latest, ethco/jlinkmc:jdk15, ethco/jlinkmc:stable
          cache-from: type=local,src=./.buildx-cache
          cache-to: type=local,dest=./builds/stable/.buildx-cache
          # intentionally no output- built image dies with the VM
