name: Autobuild
on:
  schedule:
    - cron: '11 23 * * *'

  # Run tests for any PRs.
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the builder
        run: |
          docker build -t bone4cmdr/jlinkmc:builder ./sandbox
          docker run --name buildercon bone4cmdr/jlinkmc:builder
          docker cp buildercon:/working/template ./Dockerfile
      - name: Preserve the updated template, in case needed
        uses: actions/upload-artifact@v1
        with:
          name: new-template
          path: Dockerfile

  # Try to build different containers using script-built template container.
  teststable:
    needs: prepare
    runs-on: ubuntu-latest
    env:
      javadk: 14
    steps:
      - uses: actions/checkout@v2
      - name: Attempt to build the stable image
        run: |
          docker build --build-arg JDK_VERSION=$javadk -t ethco/jlinkmc:jdk$javadk .
  testoldstable:
    needs: prepare
    runs-on: ubuntu-latest
    env:
      javadk: 13
    steps:
      - uses: actions/checkout@v2
      - name: Attempt to build the old stable image
        run: |
          docker build --build-arg JDK_VERSION=$javadk -t ethco/jlinkmc:jdk$javadk .
  testea:
    runs-on: ubuntu-latest
    env:
      javadk: 15
    steps:
      - uses: actions/checkout@v2
      - name: Attempt to build the early access image
        run: docker build -t ethco/jlinkmc:jdk$javadk ./ea
  pushstable:
    # Ensure test job passes before pushing image.
    needs: teststable
    name: Push and tag stable Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ethco/jlinkmc
          tags: stable,jdk14,latest
          build_args: JDK_VERSION=14
  pusholdstable:
    needs: testoldstable
    name: Push and tag old stable Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ethco/jlinkmc
          tags: oldstable,jdk13
          build_args: JDK_VERSION=13
  pushea:
    needs: testea
    name: Push and tag early access Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ethco/jlinkmc
          tags: ea,jdk15
          dockerfile: ./ea/Dockerfile
