name: Docker
on:
  push:
    branches:
      - master
      - next-jdk

jobs:
  prepare:
    name: Build the builder and update the template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build and run the builder
        run: |
          docker build -t bone4cmdr/jlinkmc:builder ./sandbox
          docker run --name buildercon bone4cmdr/jlinkmc:builder
      - name: Grab built files
        run: |
          docker cp buildercon:/working/template ./builds/oldstable/Dockerfile
          docker cp buildercon:/working/template ./builds/stable/Dockerfile
      - name: Commit changes to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Templates updated!" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  # Try to build different containers using script-built template container.
  trystable:
    needs: prepare
    name: Build the stable image, then tag and push to Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ethco/jlinkmc
          tags: stable,jdk15,latest
          build_args: JDK_VERSION=15
          dockerfile: ./builds/stable/Dockerfile

  tryoldstable:
    needs: prepare
    name: Build the old stable image, then tag and push to Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ethco/jlinkmc
          tags: oldstable,jdk14
          build_args: JDK_VERSION=14
          dockerfile: ./builds/oldstable/Dockerfile

  # JDK16 doesn't need the builder script due to native muslc code
  tryea:
    name: Build the early access image, then tag and push to Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ethco/jlinkmc
          tags: ea,jdk16
          dockerfile: ./builds/ea/Dockerfile
