name: Build and cache the Docker container

on:
  push:
    branches:
      - testing

jobs:
  trystable:
    # needs: prepare
    name: Build and tag the stable image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          # TODO optimize the caching process
          # this cache still won't help with repeated downloads, but that's
          # an issue that can only be solved with scripting, not in Actions
          path: /cache/.buildx-cache
          key: buildx-stable-${{ github.sha }}
          restore-keys: |
            buildx-stable-
            buildx-
      # skip the login because we aren't pushing to registry?
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and cache the stable container
        uses: docker/build-push-action@v2
        with:
          context: /builds/stable
          build-args: JDK_VERSION=15
          tags: ethco/jlinkmc:latest, ethco/jlinkmc:jdk15, ethco/jlinkmc:stable
          cache-from: type=local,src=/cache/.buildx-cache
          cache-to: type=local,dest=/cache/.buildx-cache
          # we don't actually output this image anywhere... but we don't need to
          # it dies with the VM, but the cache used to create it will persist
