name: Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron: '00 12 * * 6'

  # Run tests for any PRs.
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Dockerfile using shell script and template
        run: |
          docker build -t bone4cmdr/jlinkmc:builder ./builder
          docker run --name buildercon bone4cmdr/jlinkmc:buildercon
      - name: Retrieve prepared Dockerfile
        run: docker cp buildercon:/working/template ./builder/output/Dockerfile

  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [14, 13, 9, 15ea]
    steps:
      - uses: actions/checkout@v2
      - name: Test building using selected JDKs
        env: javadk: ${{ matrix.jdk }}
        run: |
          docker build --build-arg JDK_VERSION=$javadk -t ethco/jlinkmc:jdk$javadk

  push:
    # Ensure test job passes before pushing image.
    needs: test
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      # TODO: research this action
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ethco/jlinkmc
