name: MigrationTest
on:
  push:
    branches:
      - testing

jobs:
  # Try to build the stable container using the new action
  # tryea would have been simpler, but trystable is more representative
  teststable:
    name: Build the stable image, then tag and push to Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./builds/stable/Dockerfile
          push: true
          build-args: JDK_VERSION=15
          # replace this ASAP with no-cache: true
          tags: ethco/jlinkmc:latest
