name: MigrationTest
on:
  push:
    branches:
      - testing

jobs:
  # this job shouldn't need to change at all
  prepare:
    name: Build the builder and update the template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: testing
      - name: Build and run the builder
        run: |
          docker build -t bone4cmdr/jlinkmc:builder ./sandbox
          docker run --name buildercon bone4cmdr/jlinkmc:builder
      - name: Grab built files
        run: |
          docker cp buildercon:/working/template ./builds/oldstable/Dockerfile
          docker cp buildercon:/working/template ./builds/stable/Dockerfile
      - name: Commit changes to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Templates updated!" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: testing

  # Try to build the stable container using the new action
  # tryea would have been simpler, but trystable is more representative
  teststable:
    needs: prepare
    name: Build the stable image, then tag and push to Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: testing
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./builds/stable/Dockerfile
          pull: true
          push: true
          build-args: JDK_VERSION=15
          # replace this ASAP with no-cache: true
          cache-from: type=registry,ref=ethco/jlinkmc:stable
          cache-to: type=inline
          tags: ethco/jlinkmc:stable,jdk15,latest
